import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { OPTIONS } from "./api/auth/[...nextauth]/route";
import { NextAuthAndStoreProvider } from "./NextAuthAndStoreProvider";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getServerSession(OPTIONS);

  return (
    <html lang="en">
      <body className={lexend.className}>
        <NextAuthAndStoreProvider session={session} font={lexend}>
          {children}
        </NextAuthAndStoreProvider>
      </body>
    </html>
  );
}
