import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { getServerSession } from "next-auth";
import { NextAuthAndStoreProvider } from "./NextAuthAndStoreProvider";
import { OPTIONS } from "@/util/authOptions";
import Script from "next/script";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gammoda Software",
  description: "Generated by Gammoda Software",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        {/* Google Analytics */}
        {/* <Script
          src={`https://www.googletagmanager.com/gtag/js?id=YOUR_TRACKING_ID`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'YOUR_TRACKING_ID', {
              page_path: window.location.pathname,
            });
          `}
        </Script> */}
        <NextAuthAndStoreProvider font={lexend}>
          {children}
        </NextAuthAndStoreProvider>
      </body>
    </html>
  );
}
