import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import { getServerSession } from "next-auth";
import { NextAuthAndStoreProvider } from "./NextAuthAndStoreProvider";
import { OPTIONS } from "@/util/authOptions";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gammoda Software",
  description: "Generated by Gammoda Software",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <NextAuthAndStoreProvider font={lexend}>
          {children}
        </NextAuthAndStoreProvider>
      </body>
    </html>
  );
}
